# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = JumpButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 510, 789, 27))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = JobsQTabsWidget(self.layoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 743, 24))
        self.menubar.setObjectName("menubar")
        self.createJobsMenubar = QtWidgets.QMenu(self.menubar)
        self.createJobsMenubar.setObjectName("createJobsMenubar")
        self.menuDocumentation = QtWidgets.QMenu(self.menubar)
        self.menuDocumentation.setObjectName("menuDocumentation")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.ActionImportFromMail = QtWidgets.QAction(MainWindow)
        self.ActionImportFromMail.setCheckable(False)
        self.ActionImportFromMail.setObjectName("ActionImportFromMail")
        self.ActionSelectFile = QtWidgets.QAction(MainWindow)
        self.ActionSelectFile.setObjectName("ActionSelectFile")
        self.action3D_printers = QtWidgets.QAction(MainWindow)
        self.action3D_printers.setObjectName("action3D_printers")
        self.actionPMMA_Laser_cutter = QtWidgets.QAction(MainWindow)
        self.actionPMMA_Laser_cutter.setObjectName("actionPMMA_Laser_cutter")
        self.actionMetal_Laser_Cutter = QtWidgets.QAction(MainWindow)
        self.actionMetal_Laser_Cutter.setObjectName("actionMetal_Laser_Cutter")
        self.createJobsMenubar.addAction(self.ActionImportFromMail)
        self.createJobsMenubar.addAction(self.ActionSelectFile)
        self.menuDocumentation.addAction(self.action3D_printers)
        self.menuDocumentation.addAction(self.actionPMMA_Laser_cutter)
        self.menuDocumentation.addAction(self.actionMetal_Laser_Cutter)
        self.menubar.addAction(self.createJobsMenubar.menuAction())
        self.menubar.addAction(self.menuDocumentation.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "BUTTOn"))
        self.createJobsMenubar.setTitle(_translate("MainWindow", "Create Jobs"))
        self.menuDocumentation.setTitle(_translate("MainWindow", "Documentation"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.ActionImportFromMail.setText(_translate("MainWindow", "Import from Mail"))
        self.ActionSelectFile.setText(_translate("MainWindow", "Select FIle"))
        self.action3D_printers.setText(_translate("MainWindow", "3D printers"))
        self.actionPMMA_Laser_cutter.setText(_translate("MainWindow", "PMMA Laser cutter"))
        self.actionMetal_Laser_Cutter.setText(_translate("MainWindow", "Metal Laser Cutter"))
from jobsQTabsWidget import JobsQTabsWidget
from myWidgets import JumpButton
